# Generated by Django 3.2.14 on 2024-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('numeroDocumento', models.CharField(max_length=10)),
                ('tipoDocumento', models.IntegerField(choices=[(1, 'cedula ciudadania'), (2, 'tarjeta de identidad'), (3, 'cedula extranjera'), (4, 'pasaporte')])),
            ],
        ),
    ]
